springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
